<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('cong_no_table', 'export')">export</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">CHI NHÀ CUNG CẤP</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<!-- 
<table id="cong_no_table" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nhà cung cấp</th>
      <th>Ngày</th>      
      <th class="hidden-xs">Nợ đầu kì</th>
      <th class="hidden-xs">Nợ phát sinh</th> 
      <th>Nợ cuối kì</th>    
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_cong_no as $cong_no) { ?>
    <tr>
      	<td>
      		<a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-nha-cung-cap', 'id'=>$cong_no['id_nha_cung_cap'])); ?>"><?php echo $cong_no['ho_ten']; ?></a> 
      	</td>
      	<td><?php $date = new DateTime($cong_no['ki']); echo $date->format('d-m-Y'); ?></td>
      	<td class="hidden-xs"><?php echo number_format($cong_no['no_dau_ki'],0,","," "); ?></td>
      	<td class="hidden-xs"><?php echo number_format($cong_no['no_phat_sinh'],0,","," "); ?></td>
      	<td>
      		<?php 
      			$no_cuoi_ki=(float)$cong_no['no_dau_ki']+(float)$cong_no['no_phat_sinh']; 
      			echo number_format($no_cuoi_ki,0,","," ");
      		?>
      	</td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
-->

<table id="cong_no_table" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Mã phiếu chi</th>
      <th>Ngày</th> 
      <th class="hidden-xs">Diễn giải</th>           
      <th class="hidden-xs">Số tiền</th>   
    </tr>
  </thead>     
  <tbody>
    <?php
    foreach ($danh_sach_phieu_chi as $key => $phieu_chi) {
      ?>
      <tr>
        <td><?php echo $phieu_chi['ma']; ?></td>
        <td>
        <?php
          $date=new DateTime($phieu_chi['ngay_thanh_toan']); 
          echo $date->format('d-m-Y'); 
        ?>
        </td>
        <td><?php echo $phieu_chi['ly_do']; ?></td>
        <td><?php echo number_format($phieu_chi['so_tien'],0,","," "); ?></td>
      </tr>
      <?php
    }
    ?>
  </tbody>
</table>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#cong_no_table").DataTable({
      responsive: true,
      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
    });
  })
</script>