
<style type="text/css">   
    @media print {
        #header, .nav-side-menu, #alert, #btn-flash-messenger, .alert, #btn_print, form{display: none; }
        table.table.table-hover.table-bordered {
        	display: table; 
        	border-spacing: 0px;
		    width: 100%;
        }   

        .text-center{
        	text-align: center;
        }    
    }
</style>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">TỔNG HỢP THU CHI</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<?php
$form=$this->form;
$form->setAttribute('action', $this->url("thanh_toan", array('action'=>'index')));
$form->setAttribute('class','form');
$form->setAttribute('role','form');
$form->setAttribute('method','post');
$form->prepare();
echo $this->form()->openTag($form);
?>
	<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
		<div class="form-group">
	      <label><?php echo $this->formLabel($form->get('thoi_gian_bat_dau')); ?></label>
	      <?php echo $this->formInput($form->get('thoi_gian_bat_dau')); ?>
	      <div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('thoi_gian_bat_dau')); ?>
	      </div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
		<div class="form-group">
	      <label><?php echo $this->formLabel($form->get('thoi_gian_ket_thuc')); ?></label>
	      <?php echo $this->formInput($form->get('thoi_gian_ket_thuc')); ?>
	      <div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('thoi_gian_ket_thuc')); ?>
	      </div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 text-right">
		<div class="form-group">
			<label>&nbsp;</label><br>
			<button class="btn btn-danger">Tìm</button>
			<a class="btn btn-default" id="btn_print">In</a>
		</div>
	</div>	
<?php echo $this->form()->closeTag($form); ?>
<div class="document-print">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<h3>
			<b>NHÀ SÁCH VINH QUANG<br>
			45A Phạm Ngũ Lão, Phường 1, TP. Trà Vinh
			</b>
		</h3>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
		<h3>
			<b>SỔ QUỸ TIỀN MẶT</b><br>			
			<small>Ngày <?php echo date('d', time()); ?> Tháng <?php echo date('m', time()); ?> Năm <?php echo date('Y', time()); ?></small>
		</h3>
	</div>	
	<table border="1" id="tbSanPham" width="100%" cellspacing="0"> <!--  table-striped -->
	  <thead>
	  	<tr>
	      <th colspan="2" class="text-center">Chứng từ</th>
	      <th class="text-center">Diễn giải</th>
	      <th colspan="2" class="text-center">Phát sinh</th>
	    </tr>
	    <tr>
	      <th class="text-center">Ngày</th>
	      <th class="text-center">Số</th>
	      <th class="text-center">Lý do</th>
	      <th class="text-center">Thu</th> 
	      <th class="text-center">Chi</th>    
	    </tr>
	  </thead>     
	  <tbody>
	  <?php foreach ($this->danh_sach_thu_chi as $thu_chi) { ?>
	    <tr>
	      	<td class="text-center">
	      		<?php 
	      			$date=new DateTime($thu_chi['ngay_thanh_toan']); 
	      			echo $date->format('d-m-Y');
	      		?>
	      	</td>
	      	<td class="text-center"><?php echo $thu_chi['ma']; ?></td>
	      	<td><?php echo $thu_chi['ly_do']; ?></td>
	      	<td class="text-center">
	      		<?php 
	      			$co=0;
	      			if($co==0 and $thu_chi['loai']=='phieu_thu'){
	      				$co=1;
	      				echo number_format($thu_chi['so_tien'],0,","," ");	
	      			}      			
	      		?>
	      	</td>
	      	<td class="text-center">
	      		<?php 
	      			if($co==0 and $thu_chi['loai']=='phieu_chi'){
	      				$co=1;
	      				echo number_format($thu_chi['so_tien'],0,","," ");	
	      			}      			
	      		?>
	      	</td>
	    </tr>
	  <?php }?>                  
	  </tbody>
	</table>
</div>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#btn_print').on('click', function(){
			window.print();
		});
	})
</script>
