<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">PHIẾU THU</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<?php
$form=$this->form;
$form->setAttribute('action', $this->url("thanh_toan", array('action'=>'lap-phieu-thu')));
$form->setAttribute('class','form');
$form->setAttribute('role','form');
$form->setAttribute('method','post');
$form->prepare();
echo $this->form()->openTag($form);
?>
	<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
		<div class="form-group">
	      	<label><?php echo $this->formLabel($form->get('ho_ten')); ?></label>
	      	<?php echo $this->formInput($form->get('ho_ten')); ?>
	      	<div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('ho_ten')); ?>
	      	</div>
	    </div>
	    <div class="form-group">
	      	<label>Nợ đầu kì</label>
	      	<input type="text" id="no_dau_ki" disabled class="form-control">
	      	<div class="text-danger" id="error_no_dau_ki"></div>
	    </div>
	    <div class="form-group">
	      	<label>Nợ phát sinh</label>
	      	<input type="text" id="no_phat_sinh" disabled class="form-control">
	      	<div class="text-danger" id="error_no_phat_sinh"></div>
	    </div>
	    <div class="form-group">
	      	<label>Nợ cuối kì</label>
	      	<input type="text" id="no_cuoi_ki" disabled class="form-control">
	      	<div class="text-danger" id="error_no_cuoi_ki"></div>
	    </div>
	    <div class="form-group">
	      	<label><?php echo $this->formLabel($form->get('so_tien')); ?></label>
	      	<?php echo $this->formInput($form->get('so_tien')); ?>
	      	<div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('so_tien')); ?>
	      	</div>
	    </div>
	    <div class="form-group">
	      	<label>Dư nợ</label>
	      	<input type="text" id="du_no" disabled class="form-control">
	      	<div class="text-danger" id="error_du_no"></div>
	    </div>
	    <div class="form-group">
	      	<label><?php echo $this->formLabel($form->get('ly_do')); ?></label>
	      	<?php echo $this->formInput($form->get('ly_do')); ?>
	      	<div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('ly_do')); ?>
	      	</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 text-right">
	    <button type="reset" class="btn btn-default">Tạo lại</button>	    
	    <button class="btn btn-danger">Lưu</button>
	</div>

<?php echo $this->form()->closeTag($form); ?>