<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">LẬP PHIẾU THU</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<?php
$form=$this->form;
$form->setAttribute('action', $this->url("thanh_toan", array('action'=>'lap-phieu-thu')));
$form->setAttribute('class','form');
$form->setAttribute('role','form');
$form->setAttribute('method','post');
$form->prepare();
echo $this->form()->openTag($form);
$form->get('id_khach_hang')->setAttribute('id','id_khach_hang');
echo $this->formHidden($form->get('id_khach_hang'));
?>
	<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
		<div class="form-group">
	      	<label><?php echo $this->formLabel($form->get('ho_ten')); ?></label>
	      	<div class="filter">
	      		<?php
	      			$form->get('ho_ten')->setAttribute('data-action','filter');
	      			$form->get('ho_ten')->setAttribute('data-filters','#danh_sach_khach_hang');
	      			echo $this->formInput($form->get('ho_ten')); 
	      		?>
	      		<table class="table table-hover cursor dev-table" id="danh_sach_khach_hang">
			        <tbody>
			        </tbody>
			    </table>
	      	</div>
	      	<div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('ho_ten')); ?>
	      	</div>
	    </div>
	    <div class="form-group">
	      	<label>Nợ đầu kì</label>
	      	<input type="text" id="no_dau_ki" disabled class="form-control">
	      	<div class="text-danger" id="error_no_dau_ki"></div>
	    </div>
	    <div class="form-group">
	      	<label>Nợ phát sinh</label>
	      	<input type="text" id="no_phat_sinh" disabled class="form-control">
	      	<div class="text-danger" id="error_no_phat_sinh"></div>
	    </div>
	    <div class="form-group">
	      	<label>Nợ cuối kì</label>
	      	<input type="text" id="no_cuoi_ki" disabled class="form-control">
	      	<div class="text-danger" id="error_no_cuoi_ki"></div>
	    </div>
	    <div class="form-group">
	      	<label><?php echo $this->formLabel($form->get('so_tien')); ?></label>
	      	<?php echo $this->formInput($form->get('so_tien')); ?>
	      	<div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('so_tien')); ?>
	      	</div>
	    </div>
	    <div class="form-group">
	      	<label>Dư nợ</label>
	      	<input type="text" id="du_no" disabled class="form-control">
	      	<div class="text-danger" id="error_du_no"></div>
	    </div>
	    <div class="form-group">
	      	<label><?php echo $this->formLabel($form->get('ly_do')); ?></label>
	      	<?php echo $this->formInput($form->get('ly_do')); ?>
	      	<div class="text-danger">
	        <?php echo $this->formElementErrors($form->get('ly_do')); ?>
	      	</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 text-right">
	    <button type="reset" class="btn btn-default">Tạo lại</button>	    
	    <button class="btn btn-danger">Lưu</button>
	</div>

<?php echo $this->form()->closeTag($form); ?>
<script type="text/javascript">
	jQuery(document).ready(function(){
		var xhr1;           
	    if(xhr1 && xhr1.readyState != 4){
	        xhr1.abort(); //huy lenh ajax truoc do
	    }
	    xhr1 = $.ajax({
	        url:"<?php echo $this->url('thanh_toan', array('action'=>'danh-sach-khach-hang')); ?>",
	        type:'POST',
	        dataType:'json',
	        data:{
	            
	        },
	        success:function(data){
	        	jQuery.each( data.danh_sach_khach_hang, function( key, value){
	        		var tr='<tr style="width:100%;">'
	        			+ 	'<td style="width:30%;"><span class="id_khach_hang hidden-xs hidden-sm hidden-md hidden-lg">'+value.id_khach_hang+'</span><span class="ho_ten">'+value.ho_ten+'<span></td>'
	        			+   '<td style="width:50%;">'+value.dia_chi+'</td>'
	        			+   '<td style="width:20%;">'+value.di_dong+'</td>'
	        			+ '</tr>';
	        		jQuery('#danh_sach_khach_hang tbody').append(tr);
	        	});
	        	jQuery('#danh_sach_khach_hang tbody tr').on('click', function(){
	        		var id_khach_hang=jQuery(this).find('.id_khach_hang').text().trim();
	        		var ho_ten=jQuery(this).find('.ho_ten').text().trim();
	        		jQuery('#id_khach_hang').val(id_khach_hang);
	        		jQuery('#ho_ten').val(ho_ten);
	        		var xhr2;           
				    if(xhr2 && xhr2.readyState != 4){
				        xhr2.abort(); //huy lenh ajax truoc do
				    }
				    xhr2 = $.ajax({
				        url:"<?php echo $this->url('thanh_toan', array('action'=>'cong-no-khach-hang')); ?>",
				        type:'POST',
				        dataType:'json',
				        data:{
				            'id_khach_hang':id_khach_hang,
				        },
				        success:function(data){
				        	jQuery.each( data.danh_sach_cong_no, function( key, value){
				        		jQuery('#no_dau_ki').val(value.du_no);
				        		jQuery('#no_phat_sinh').val(value.no_phat_sinh);
				        		var no_cuoi_ki=parseInt(value.du_no)+parseInt(value.no_phat_sinh);
				        		jQuery('#no_cuoi_ki').val(no_cuoi_ki);


				        	});
				        },
				        error:function(){

				        }
				    });
	        		
	        	});
	        },
	        error: function(){
	        	
	        }
	    });
		jQuery('#so_tien').on('change', function(){
			var no_cuoi_ki=jQuery('#no_cuoi_ki').val().trim();
			if(no_cuoi_ki!=''){
				var so_tien=jQuery(this).val();
				var du_no=no_cuoi_ki-so_tien;
				if(du_no>=0 && du_no<no_cuoi_ki){
					jQuery('#du_no').val(du_no);
				}
				else{
					alert('Số tiền thanh toán không được vượt quá số nợ hoặc không được bằng 0 hoặc số ăm');
				}				
			}
		});
			
	})
</script>