<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default">export</div>
  <a href="<?php echo $this->url('chi_nhanh', array('action'=>'tao-chi-nhanh')); ?>" class="btn btn-danger">Thêm</a>  
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">CHI NHÁNH</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%"> <!--  table-striped -->
  <thead>
    <tr>
      <th>Tên chi nhánh</th>
      <th class="hidden-xs">Địa chỉ</th>
      <th>Quản lý</th> 
      <th>Sửa</th>    
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_kho as $key => $kho) { ?>
    <tr>
      <td><?php echo $kho['ten_kho']; ?></td>
      <td class="hidden-xs"><?php echo $kho['dia_chi_kho']; ?></td>
      <td><a href="<?php echo $this->url('chi_nhanh', array('action'=>'quan-ly-chi-nhanh','id'=>$kho['id_kho'])); ?>">Quản lý</a></td>
      <td><a href="<?php echo $this->url('chi_nhanh', array('action'=>'sua-chi-nhanh', 'id'=>$kho['id_kho'])); ?>">Sửa</a></td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
    });
  })                
</script>