<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default">export</div>  
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">CHI NHÁNH</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%"> <!--  table-striped -->
  <thead>
    <tr>
      <th>Tên chi nhánh</th>
      <th>Địa chỉ</th>
      <th>Quản lý</th> 
      <th>Sửa</th>    
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_kho as $key => $kho) { ?>
    <tr>
      <td><?php echo $kho['ten_kho']; ?></td>
      <td><?php echo $kho['dia_chi_kho']; ?></td>
      <td><a href="<?php echo $this->url('chi_nhanh', array('action'=>'quan-ly-chi-nhanh','id'=>$kho['id_kho'])); ?>">Quản lý</a></td>
      <td><a href="#" data-toggle="modal" data-target="#myModal">Sửa</a></td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <?php
    // $form=$this->form;
    // $form->setAttribute('action', $this->url("chi_nhanh", array('action'=>'sua-chi-nhanh')));
    // $form->setAttribute('class','form');
    // $form->setAttribute('role','form');
    // $form->setAttribute('method','post');
    // $form->prepare();
    // echo $this->form()->openTag($form);
    // $form->get('id_kenh_phan_phoi')->setAttribute('id','id_kenh_phan_phoi');
    // echo $this->formHidden($form->get('id_kenh_phan_phoi'));
    ?>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> 
          <h3 class="modal-title">Cập nhật thông tin chi nhánh</h3>              
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label><?php //echo $this->formLabel($form->get('chiet_khau_xuong')); ?></label>
            <?php 
            //$form->get('chiet_khau_xuong')->setAttribute('id','chiet_khau_xuong');
            //echo $this->formInput($form->get('chiet_khau_xuong')); 
            ?>
            <div class="text-danger">
              <?php //echo $this->formElementErrors($form->get('chiet_khau_xuong')); ?>
            </div>
          </div>          
        </div>
        <div class="modal-footer">
          <a type="button" class="btn btn-default" data-dismiss="modal">Close</a>
          <button type="submit" class="btn btn-danger">Lưu</button>
        </div>
      </div>
    <?php //echo $this->form()->closeTag($form); ?>
  </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
    });
  })                
</script>