<?php
$form=$this->form;
$form->setAttribute('action', $this->url("chi_nhanh", array('action'=>'tao-chi-nhanh')));
$form->setAttribute('class','form');
$form->setAttribute('role','form');
$form->setAttribute('method','post');
$form->prepare();
echo $this->form()->openTag($form);
?>  
  <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
    <span class="title">THÊM CHI NHÁNH</span>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
  <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
    <div class="form-group">
      <label><?php echo $this->formLabel($form->get('ten_kho')); ?></label>
      <?php echo $this->formInput($form->get('ten_kho')); ?>
      <div class="text-danger">
        <?php echo $this->formElementErrors($form->get('ten_kho')); ?>
      </div>
    </div>
    <div class="form-group">
      <label><?php echo $this->formLabel($form->get('dia_chi_kho')); ?></label>
      <?php echo $this->formInput($form->get('dia_chi_kho')); ?>
      <div class="text-danger">
        <?php echo $this->formElementErrors($form->get('dia_chi_kho')); ?>
      </div>
    </div>

  </div>
  <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 text-right">
    <a class="btn btn-default" href="<?php echo $this->url('chi_nhanh'); ?>">Quay lại</a>
    <button class="btn btn-danger">Lưu</button>
  </div>
<?php
echo $this->form()->closeTag($form);
?>