<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
  <a href="<?php echo $this->url('doi_tac', array('action'=>'them-khach-hang')); ?>" class="btn btn-danger"><span class="hidden-xs">Thêm khách hàng</span><span class="hidden-sm hidden-md hidden-lg">Thêm KH</span></a>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">KHÁCH HÀNG</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Tên khách hàng</th>
      <th class="hidden-xs">Điện thoại</th>
      <th class="hidden-xs hidden-sm">Địa chỉ</th>
      <th>Kênh phân phối</th>
      <th>Thống kê</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_khach_hang as $key => $khach_hang) { ?>
    <tr>
      <td><a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-khach-hang', 'id'=>$khach_hang['id_khach_hang'])); ?>"><?php echo $khach_hang['ho_ten']; ?></a></td>
      <td class="hidden-xs"><?php echo $khach_hang['di_dong']; ?></td>
      <td class="hidden-xs hidden-sm"><?php echo $khach_hang['dia_chi']; ?></td>
      <td><?php echo $khach_hang['kenh_phan_phoi']; ?></td>
      <td><a href="#" data="<?php echo $khach_hang['id_khach_hang']; ?>" class="ajax-data">Thống kê</a></td>
      <!-- data-toggle="modal" data-target="#myModal" -->
    </tr>
  <?php }?>                  
  </tbody>
</table>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="table-responsive">
          <table class="table table-hover cursor">
            <thead>
              <tr>
                <th colspan="2">Thống kê</th>
              </tr>
            </thead>
            <tbody>
              <tr id="tr-so-hoa-don">
                <td>Tổng số hóa đơn: </td>
                <td><span id="so-hoa-don" class="label label-success">0</span></td>
              </tr>
              <tr>
                <td>Tổng nợ: </td>
                <td><span id="tong-no" class="label label-danger">0</span></td>
              </tr>
            </tbody>              
          </table>
        </div>        
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
    });
    jQuery('#example_wrapper>div:first-child>div:first-child').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:first-child').addClass('col-sm-5');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').addClass('col-sm-7');

    jQuery('.ajax-data').on('click', function(){
      var xhr1;   
      var id_khach_hang= jQuery(this).attr('data');      
      if(xhr1 && xhr1.readyState != 4){
          xhr1.abort(); //huy lenh ajax truoc do
      }

      xhr1 = $.ajax({
          url:"<?php echo $this->url('doi_tac', array('action'=>'cong-no-khach-hang')); ?>",
          type:'POST',
          dataType:'json',
          data:{
              'id_khach_hang':  jQuery(this).attr('data'),
          },
          success:function(data){
            if(data.error==''){
              jQuery('#so-hoa-don').text(data.so_hoa_don);
              jQuery('#tong-no').text(data.tong_no);
              jQuery('#tr-so-hoa-don').attr('onclick','setLocation("/ban-hang/hoa-don/'+id_khach_hang+'")');
              jQuery('#myModal').modal();
            }
            else{
              jQuery('#alert').attr('class','alert alert-danger').children('span').text(data.error);
              jQuery('#alert').show('slow').delay(3000).hide('slow');
            }            
          },
          error:function(){
            jQuery('#alert').attr('class','alert alert-danger').children('span').text('Lỗi');
            jQuery('#alert').show('slow').delay(3000).hide('slow');
          }
      });   
    });
        
  })                
</script>