<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
  <a href="<?php echo $this->url('doi_tac', array('action'=>'them-khach-hang')); ?>" class="btn btn-danger">Thêm khách hàng</a>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">KHÁCH HÀNG</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Tên khách hàng</th>
      <th class="hidden-xs">Điện thoại</th>
      <th class="hidden-xs hidden-sm">Địa chỉ</th>
      <th>Kênh phân phối</th>
      <th>Thống kê</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_khach_hang as $key => $khach_hang) { ?>
    <tr>
      <td><a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-khach-hang', 'id'=>$khach_hang['id_khach_hang'])); ?>"><?php echo $khach_hang['ho_ten']; ?></a></td>
      <td class="hidden-xs"><?php echo $khach_hang['di_dong']; ?></td>
      <td class="hidden-xs hidden-sm"><?php echo $khach_hang['dia_chi']; ?></td>
      <td><?php echo $khach_hang['kenh_phan_phoi']; ?></td>
      <td><a href="#<?php echo $khach_hang['id_khach_hang']; ?>">Thống kê</a></td>
    </tr>
  <?php }?>                  
  </tbody>
</table>

<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
    });
    jQuery('#example_wrapper>div:first-child>div:first-child').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:first-child').addClass('col-sm-5');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').addClass('col-sm-7');
  })                
</script>