<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
  <a href="<?php echo $this->url('doi_tac', array('action'=>'them-nha-cung-cap')); ?>" class="btn btn-danger"><span class="hidden-sm hidden-md hidden-lg">Thêm</span><span class="hidden-xs">Thêm nhà cung cấp</span></a>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">NHÀ CUNG CẤP</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Tên nhà cung cấp</th>
      <th>Điện thoại</th>
      <th class="hidden-xs hidden-sm">Địa chỉ</th>
      <th>Thống kê</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_nha_cung_cap as $key => $nha_cung_cap) { ?>
    <tr>
      <td><a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-nha-cung-cap', 'id'=>$nha_cung_cap['id_nha_cung_cap'])); ?>"><?php echo $nha_cung_cap['ho_ten']; ?></a></td>
      <td><?php echo $nha_cung_cap['di_dong']; ?></td>
      <td class="hidden-xs hidden-sm"><?php echo $nha_cung_cap['dia_chi']; ?></td>
      <td><a href="#" data="<?php echo $nha_cung_cap['id_nha_cung_cap']; ?>" class="ajax-data">Thống kê</a></td>
    </tr>
  <?php }?>                  
  </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>        
        <div class="table-responsive">
          <table class="table table-hover cursor">
            <thead>
              <tr>
                <th colspan="2">Thống kê</th>
              </tr>
            </thead>
            <tbody>
              <tr id="tr-so-phieu-nhap">
                <td>Tổng số phiếu nhập: </td>
                <td><span id="so-phieu-nhap" class="label label-success">0</span></td>
              </tr>
              <tr>
                <td>Tổng nợ: </td>
                <td><span id="tong-no" class="label label-danger">0</span></td>
              </tr>
            </tbody>              
          </table>
        </div> 
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
    });
    jQuery('#example_wrapper>div:first-child>div:first-child').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:first-child').addClass('col-sm-5');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').addClass('col-sm-7');
    jQuery('.ajax-data').on('click', function(){
      var xhr1;    
      var id_nha_cung_cap=jQuery(this).attr('data');       
      if(xhr1 && xhr1.readyState != 4){
          xhr1.abort(); //huy lenh ajax truoc do
      }

      xhr1 = $.ajax({
          url:"<?php echo $this->url('doi_tac', array('action'=>'cong-no-nha-cung-cap')); ?>",
          type:'POST',
          dataType:'json',
          data:{
              'id_nha_cung_cap':  jQuery(this).attr('data'),
          },
          success:function(data){
            if(data.error==''){
              jQuery('#so-phieu-nhap').text(data.so_phieu_nhap);
              jQuery('#tong-no').text(data.tong_no+' VNĐ');
              jQuery('#tr-so-phieu-nhap').attr('onclick','setLocation("/ban-hang/phieu-nhap/'+id_nha_cung_cap+'")');
              jQuery('#myModal').modal();
            }
            else{
              jQuery('#alert').attr('class','alert alert-danger').children('span').text(data.error);
              jQuery('#alert').show('slow').delay(3000).hide('slow');
            }            
          },
          error:function(){
            jQuery('#alert').attr('class','alert alert-danger').children('span').text('Lỗi');
            jQuery('#alert').show('slow').delay(3000).hide('slow');
          }
      });   
    });
  })                
</script>