<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
  <a href="<?php echo $this->url('doi_tac', array('action'=>'them-nha-cung-cap')); ?>" class="btn btn-danger"><span class="hidden-sm hidden-md hidden-lg">Thêm NCC</span><span class="hidden-xs">Thêm nhà cung cấp</span></a>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">NHÀ CUNG CẤP</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-striped table-bordered cursor" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Tên nhà cung cấp</th>
      <th>Điện thoại</th>
      <th class="hidden-xs hidden-sm">Địa chỉ</th>
      <th>Thống kê</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_nha_cung_cap as $key => $nha_cung_cap) { ?>
    <tr>
      <td><a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-nha-cung-cap', 'id'=>$nha_cung_cap['id_nha_cung_cap'])); ?>"><?php echo $nha_cung_cap['ho_ten']; ?></a></td>
      <td><?php echo $nha_cung_cap['di_dong']; ?></td>
      <td class="hidden-xs hidden-sm"><?php echo $nha_cung_cap['dia_chi']; ?></td>
      <td><a href="#<?php echo $nha_cung_cap['id_nha_cung_cap']; ?>">Thống kê</a></td>
    </tr>
  <?php }?>                  
  </tbody>
</table>

<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
    });
    jQuery('#example_wrapper>div:first-child>div:first-child').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:first-child').addClass('col-sm-5');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').addClass('col-sm-7');
  })                
</script>