<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->        
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/default/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/datatable/dataTables.bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
            
            ->prependStylesheet($this->basePath() . '/css/datetime-picker/bootstrap-datetimepicker.css')
            ->prependStylesheet($this->basePath() . '/css/custom/custom.css')
            ->prependStylesheet($this->basePath() . '/css/filterTable/filterTable.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.min.css'); 
        ?>
        <link href="<?php echo $this->basePath();?>/css/HTML5admin.css" rel="stylesheet">
        <link href="<?php echo $this->basePath();?>/css/plugins/animate.css" rel="stylesheet">

        <!-- Scripts -->
        <?php echo $this->headScript()            
            ->prependFile($this->basePath() . '/js/datatable/dataTables.bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/datatable/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/sticky/jquery.sticky.js')
            ->prependFile($this->basePath() . '/js/datetime-picker/bootstrap-datetimepicker.js')
            ->prependFile($this->basePath() . '/js/function/function.js')
            ->prependFile($this->basePath() . '/js/custom/custom.js')
            ->prependFile($this->basePath() . '/js/filterTable/filterTable.js')
            ->prependFile($this->basePath() . '/js/export/export-excel.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>
        
        

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>        
        <div id="alert" class="alert alert-success hide">
          <button type="button" class="close" data-dismiss="alert">x</button>
          <span>Thông báo</span>
        </div>
        <div id="brand" class="container hidden-xs">
          <img src="<?php echo $this->basePath(); ?>/img/default/logo/default.png" alt="..." class="img-responsive img-rounded" height="100px" width="100px">
        </div>
        <div id="header">
          <nav class="navbar navbar-default" role="navigation"><!--  navbar-fixed-top -->
            <div class="container">
              <div class="navbar-header">            
                <a class="navbar-brand" href="<?php echo $this->url('hang_hoa'); ?>"><span>Nhà Sách Vinh Quang</span></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                </ul>             
                <ul class="nav navbar-nav navbar-right">
                  <?php
                    $this->navigation()->menu()->setPartial('application/partial/menu');
                    echo $this->navigation('Navigation')->menu()->render();
                  ?>

                </ul>
              </div>
            </div>
          </nav>    

        </div><!-- header -->    
        <div id="content"> 

          <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
              <div class="nav-side-menu">
                <div class="menu-list">        
                  <ul id="menu-content" class="menu-content out"> 
                    <?php
                      $this->navigation()->menu()->setPartial('application/partial/menu_right');
                      echo $this->navigation('NavigationRight')->menu()->render();
                    ?>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-8 col-lg-9">
              <?php
                // báo cáo xử lý băng zend
                $flash=$this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                 <button type="button" id="btn-flash-messenger" class="close" data-dismiss="alert" aria-hidden="true">
                     &times;
                 </button>
                 <ul><li>')
                 ->setMessageSeparatorString('</li><li>')
                 ->setMessageCloseString('</li></ul></div>');
                 $error=$flash->render('error', array('alert', 'alert-dismissable','alert-danger'));
                 echo $error;
                 $info=$flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                 echo $info;
                 $default=$flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                 echo $default;
                 $success=$flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                 echo $success;                     
                if($error||$success||$info||$default)
                { 
                  echo "
                    <script type='text/javascript'>
                      jQuery('.alert').slideDown('slow').delay(1000).slideUp('slow');
                    </script>";                       
                }
              ?>               
              <?php echo $this->content; ?>
            </div>
          </div>             
        </div><!-- content -->
        <div id="footer">
        </div><!-- footer -->
    </body>
</html>
