<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/default/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/datatable/dataTables.bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
            
            ->prependStylesheet($this->basePath() . '/css/datetime-picker/bootstrap-datetimepicker.css')
            ->prependStylesheet($this->basePath() . '/css/custom/custom.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.min.css'); 
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()            
            ->prependFile($this->basePath() . '/js/datatable/dataTables.bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/datatable/jquery.dataTables.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
            ->prependFile($this->basePath() . '/js/sticky/jquery.sticky.js')
            ->prependFile($this->basePath() . '/js/datetime-picker/bootstrap-datetimepicker.js')
            ->prependFile($this->basePath() . '/js/function/function.js')
            ->prependFile($this->basePath() . '/js/custom/custom.js')
            ->prependFile($this->basePath() . '/js/export/export-excel.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>
        
        

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>        
        <div id="alert" class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">x</button>
          <span>Thông báo</span>
        </div>
        <div id="header">
          <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
              <div class="navbar-header">            
                <a class="navbar-brand" href=""><span>Nhà Sách Vinh Quang</span></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <!-- 
                  <li class="active"><a href="#">Link</a></li>
                  <li><a href="#">Link</a></li> 
                  -->
                </ul>
                <!-- 
                <form class="navbar-form navbar-left" role="search">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form> 
                -->
                <ul class="nav navbar-nav navbar-right">              
                  <!-- <li><a href="#" class="active"><b class="glyphicon glyphicon-qrcode"></b> <span class="hidden-sm hidden-md">Hàng hóa</span></a></li>
                  <li><a href="#"><b class="glyphicon glyphicon-signal"></b> <span class="hidden-sm hidden-md">Đối tác</span></a></li>
                  <li><a href="#"><b class="glyphicon glyphicon-scissors"></b> <span class="hidden-sm hidden-md">Chính sách</span></a></li> 
                  <li><a href="#"><b class="glyphicon glyphicon-usd"></b> <span class="hidden-sm hidden-md">Thanh toán</span></a></li>  
                  <li><a href="#"><b class="glyphicon glyphicon-shopping-cart"></b> <span class="hidden-sm hidden-md">Bán hàng</span></a></li>
                  <li><a href="#"><b class="fa fa-share-alt"></b> <span class="hidden-sm hidden-md">Chi nhánh</span></a></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="fa fa-bell shake"></b> <span class="hidden-sm hidden-md">Thông báo</span></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Quản lý tài khoản</a></li>
                      <li><a href="#">Quản lý đơn vị tính</a></li>
                      <li><a href="#">Quản lý loại hàng</a></li>
                      <li><a href="#">Quản lý mã vạch</a></li>
                      <li><a href="#">Thoát</a></li>
                    </ul>
                  </li> 
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-lg"></i> <span class="hidden-sm hidden-md">Tài khoản</span></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Quản lý tài khoản</a></li>
                      <li><a href="#">Quản lý đơn vị tính</a></li>
                      <li><a href="#">Quản lý loại hàng</a></li>
                      <li><a href="#">Quản lý mã vạch</a></li>
                      <li><a href="#">Thoát</a></li>
                    </ul>
                  </li>  -->
                  <?php
                    $this->navigation()->menu()->setPartial('application/partial/menu');
                    echo $this->navigation('Navigation')->menu()->render();
                  ?>

                </ul>
              </div>
            </div>
          </nav>    

        </div><!-- header -->    
        <div id="content"> 
            <?php echo $this->content; ?>
        </div><!-- content -->
        <div id="footer">
          
        </div><!-- footer -->
    </body>
</html>
