<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
  <a href="<?php echo $this->url('hang_hoa', array('action'=>'them-san-pham')); ?>" class="btn btn-danger">Thêm sản phẩm</a>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">HÀNG HÓA</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered cursor" cellspacing="0" width="100%"> <!--  table-striped -->
  <thead>
    <tr>
      <th>Tên sản phẩm</th>
      <th>Mã sản phẩm</th>
      <th>Tồn kho</th>
      <th class="hidden-xs">Loại</th>
      <th class="hidden-xs hidden-sm">Nhãn hàng</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_san_pham as $key => $san_pham) { ?>
    <tr onclick="setLocation('<?php echo $this->url('hang_hoa', array('action'=>'sua-san-pham', 'id'=>$san_pham['id_san_pham'])); ?>')">
      <td><?php echo $san_pham['ten_san_pham']; ?></td>
      <td><?php echo $san_pham['ma_san_pham']; ?></td>
      <td><?php echo $san_pham['ton_kho']; ?></td>
      <td class="hidden-xs"><?php echo $san_pham['loai_san_pham']; ?></td>
      <td class="hidden-xs hidden-sm"><?php echo $san_pham['nhan']; ?></td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
    }); 
    jQuery('#example_wrapper>div:first-child>div:first-child').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:first-child').addClass('col-sm-5');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').removeClass('col-sm-6');
    jQuery('#example_wrapper>div:first-child>div:nth-child(2)').addClass('col-sm-7');
  })                
</script>