<style type="text/css">
  @media print {
    div{
      display: none;
    }
  }
</style>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">NHẬP HÀNG HÓA</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Nhà cung cấp</label> 
    <div class="filter">
      <input type="text" class="form-control" id="dev-table-filter" data-action="filter" data-filters="#dev-table" placeholder="Nhập tên nhà cung cấp, số điện thoại, địa chỉ" />
      <table class="table table-hover cursor dev-table" id="dev-table">
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
  <div class="form-group">
    <label>Địa chỉ</label>
    <input type="text" id="dia_chi" title="Địa chỉ" class="form-control">
  </div>
  <div class="form-group">
    <label>Số điện thoại</label>
    <input type="text" id="di_dong" title="Số điện thoại" class="form-control">
  </div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Tên sản phẩm</label>
    <!-- dùng để lưu tạm khi chọn sản phẩm, đến khi click vào nút thểm sẽ lấy dữ liệu này ra và đưa xuống bảng danh sách sản phẩm -->
    <input type="hidden" id="id_san_pham" value="">
    <input type="hidden" id="don_vi_tinh" value="">
    <!--  -->
    <div class="filter">
      <input type="text" class="form-control" id="dev-table-filter-2" data-action="filter-2" data-filters="#dev-table-2" placeholder="Nhập tên sản phẩm, mã sản phẩm, mã vạch" />
      <table class="table table-hover cursor dev-table" id="dev-table-2">        
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
  <div class="form-group">
    <label>Mã sản phẩm</label>
    <input type="text" id="ma_san_pham" title="Mã sản phẩm" class="form-control">
  </div> 
  <div class="form-group">
    <label>Mã vạch</label>
    <input type="text" id="ma_vach" title="Mã sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label id="so_luong_ton">Số lượng</label>
    <input type="number" id="so_luong" title="Số lượng" class="form-control" min="0">
  </div>  
  <div class="form-group">
    <input type="checkbox" id="loai_gia" title="Loại giá">
    <label for="loai_gia">Sản phẩm thuộc loại giá bìa, chiết khấu (%)</label>    
  </div>         
  <div class="form-group gia_nhap">
    <label>Giá nhập sản phẩm</label>
    <input type="number" id="gia_nhap" title="Giá nhập sản phẩm" class="form-control" min="0">
  </div>
  <div class="form-group hidden-xs hidden-sm hidden-md hidden-lg gia_bia">
    <label>Giá bìa</label>
    <input type="number" id="gia_bia" title="Giá bìa" class="form-control" min="0">
  </div>
  <div class="form-group hidden-xs hidden-sm hidden-md hidden-lg gia_bia">
    <label>Chiết khấu</label>
    <input type="number" id="chiet_khau" title="Chiết khấu" class="form-control" min="0">
  </div>
  <div class="form-group">
    <div class="btn btn-danger btn-block" id="btn_them">Thêm</div>
  </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <hr>
  <span class="title">DANH SÁCH HÀNG NHẬP</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="table-responsive">
    <table class="table table-border" id="danh_sach_san_pham_nhap">
      <thead>
        <tr class="active">
          <th>Sản phẩm</th>
          <th>Đơn vị tính</th>
          <th>Số lượng</th>
          <th>Giá</th>
          <th>Hủy</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr> -->
      </tbody>
    </table>
  </div>            
</div> 
<form action="<?php echo $this->url('hang_hoa', array('action'=>'nhap-hang-hoa')); ?>" method="post" name="xuat_hang_hoa" id="xuat_hang_hoa" class="hidden-xs hidden-sm hidden-md hidden-lg" target='_blank'>
  <input type="text" name="id_nha_cung_cap" id="id_nha_cung_cap" value="0">
  <div id="danh_sach_san_pham">
    
  </div>
</form>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="btn btn-default" id="btn_huy_don_hang">Hủy đơn hàng</div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-right">
  <div class="btn btn-danger" id="btn_in_don_hang">In đơn hàng</div>
</div>
<script type="text/javascript">
  // nhập hàng
  jQuery(document).ready(function(){
    // lấy dữ liệu nhà cung cấp
      var xhr1;           
      if(xhr1 && xhr1.readyState != 4){
        xhr1.abort(); //huy lenh ajax truoc do
      }
      xhr1 = $.ajax({
        url:"<?php echo $this->url('hang_hoa', array('action'=>'danh-sach-nha-cung-cap')); ?>",
        type:'POST',
        dataType:'json',
        data:{
            
        },
        success:function(data){
          if(data.error==''){
            jQuery.each( data.danh_sach_nha_cung_cap, function( key, value){
              var tr='<tr>'
                    +   '<td data-title="Tên nhà cung cấp" style="width:40%;"><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.id_nha_cung_cap+'</div><div>'+value.ho_ten+'<div></td>'
                    +   '<td data-title="Mobile (RM/30sec)" class="numeric" style="width:20%;">'+value.di_dong+'</td>'
                    +   '<td data-title="Địa chỉ" style="width:40%;">'+value.dia_chi+'</td>';
              jQuery('#dev-table tbody').append(tr);
            });
            // chọn nhà cung cấp
              jQuery('#dev-table tbody tr').on('click', function(){
                // xóa tất cả các danh sách hàng đã chọn
                jQuery('#danh_sach_san_pham_nhap tbody tr').html('');
                jQuery('#danh_sach_san_pham').html('');
                jQuery('#dev-table-filter-2').val('');
                jQuery('#ma_san_pham').val('');
                jQuery('#ma_vach').val('');
                jQuery('#so_luong').val('');
                jQuery('#gia_nhap').val('');
                jQuery('#gia_bia').val('');
                jQuery('#chiet_khau').val('');
                
                // lấy id_nha_cung_cap mới nhất        
                var id_nha_cung_cap=jQuery(this).find('td:first-child div:first-child').text().trim();
                var ho_ten=jQuery(this).find('td:first-child div:nth-child(2)').text().trim();
                var di_dong=jQuery(this).find('td:nth-child(2)').text().trim();
                var dia_chi=jQuery(this).find('td:nth-child(3)').text().trim();
                if(jQuery.isNumeric(id_nha_cung_cap)){
                  // lưu vào form
                  jQuery('#id_nha_cung_cap').val(id_nha_cung_cap); 
                  // sửa trên giao diện
                  jQuery('#dev-table-filter').val(ho_ten);
                  jQuery('#di_dong').val(di_dong);
                  jQuery('#dia_chi').val(dia_chi);
                }
              });
          }         
        },
      });

    // lấy dữ liệu sản phẩm
      var xhr2;           
      if(xhr2 && xhr2.readyState != 4){
          xhr2.abort(); //huy lenh ajax truoc do
      }
      xhr2 = $.ajax({
        url:"<?php echo $this->url('hang_hoa', array('action'=>'danh-sach-san-pham')); ?>",
        type:'POST',
        dataType:'json',
        data:{
            
        },
        success:function(data){
          if(data.error==''){
            if(data.danh_sach_san_pham.length<=0){
              var tr='<tr style="width:100%;"><td colspan="3" style="width:100%;">Không có sản phẩm</td></tr>';
              jQuery('#dev-table-2 tbody').append(tr);
              return false;
            }
            jQuery.each( data.danh_sach_san_pham, function( key, value){
              var tr='<tr>'
                    +   '<td data-title="Tên sản phẩm" style="width:60%;"><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.id_san_pham+'</div><div>'+value.ten_san_pham+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.don_vi_tinh+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.loai_gia+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.gia_nhap+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.gia_bia+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.chiet_khau+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.ton_kho+'</div></td>'
                    +   '<td data-title="Mã sản phẩm" style="width:20%;">'+value.ma_san_pham+'</td>'
                    +   '<td data-title="Mã vạch" style="width:20%;">'+value.ma_vach+'</td>';
              jQuery('#dev-table-2 tbody').append(tr);
            });
            // chọn sản phẩm
            jQuery('#dev-table-2 tbody tr').on('click', function(){
              var id_san_pham=jQuery(this).find('td:first-child div:first-child').text().trim();
              var ten_san_pham=jQuery(this).find('td:first-child div:nth-child(2)').text().trim();
              var don_vi_tinh=jQuery(this).find('td:first-child div:nth-child(3)').text().trim();
              var loai_gia=jQuery(this).find('td:first-child div:nth-child(4)').text().trim();
              var gia_nhap=jQuery(this).find('td:first-child div:nth-child(5)').text().trim();
              var gia_bia=jQuery(this).find('td:first-child div:nth-child(6)').text().trim();
              var chiet_khau=jQuery(this).find('td:first-child div:nth-child(7)').text().trim();
              var ton_kho=jQuery(this).find('td:first-child div:nth-child(8)').text().trim();
              var ma_san_pham=jQuery(this).find('td:nth-child(2)').text().trim();
              var ma_vach=jQuery(this).find('td:nth-child(3)').text().trim();
              if(jQuery.isNumeric(id_san_pham)){
                // lưu tạm id_san_pham lại
                jQuery('#id_san_pham').val(id_san_pham);
                jQuery('#don_vi_tinh').val(don_vi_tinh);
                // đỗ dữ liệu ra form thêm
                jQuery('#dev-table-filter-2').val(ten_san_pham);
                jQuery('#ma_san_pham').val(ma_san_pham);
                jQuery('#ma_vach').val(ma_vach);
                jQuery('#gia_nhap').val(gia_nhap);
                jQuery('#gia_bia').val(gia_bia);
                jQuery('#chiet_khau').val(chiet_khau);
                jQuery('#so_luong_ton').text('Số lượng tồn: '+ton_kho);

                if(loai_gia==1){
                  jQuery('#loai_gia').prop('checked', true);
                  jQuery('.gia_nhap').addClass('hidden-xs hidden-sm hidden-md hidden-lg');
                  jQuery('.gia_bia').removeClass('hidden-xs hidden-sm hidden-md hidden-lg');
                }
                else{
                  jQuery('#loai_gia').prop('checked', false);
                  jQuery('.gia_bia').addClass('hidden-xs hidden-sm hidden-md hidden-lg');
                  jQuery('.gia_nhap').removeClass('hidden-xs hidden-sm hidden-md hidden-lg');
                }
              }

            });
          }                   
        },
      }); 

    // checkbox chọn loại giá
    jQuery('#loai_gia').on('click', function(){
      if(jQuery(this).is(':checked')){
        jQuery('.gia_nhap').addClass('hidden-xs hidden-sm hidden-md hidden-lg');
        jQuery('.gia_bia').removeClass('hidden-xs hidden-sm hidden-md hidden-lg');
      }
      else{
        jQuery('.gia_bia').addClass('hidden-xs hidden-sm hidden-md hidden-lg');
        jQuery('.gia_nhap').removeClass('hidden-xs hidden-sm hidden-md hidden-lg');
      }
    });

    // click nút thêm btn_them
    var so_dong=0;
    jQuery('#btn_them').on('click', function(){
      var id_san_pham=jQuery('#id_san_pham').val();
      var so_luong  =jQuery('#so_luong').val();
      var gia_nhap  =jQuery('#gia_nhap').val();
      var gia_bia   =jQuery('#gia_bia').val();
      var chiet_khau=jQuery('#chiet_khau').val();
      var loai_gia  =jQuery('#loai_gia').is(':checked');
      var gia=gia_nhap; // giá này để hiển thị trong bảng danh sách nhập, khi click vào nút thêm
      if(loai_gia){
        loai_gia=1;
        gia_nhap=0;
        if(gia_bia<=0 || chiet_khau<=0){
          alert('Giá bìa hoặc chiết khẩu không được nhỏ hơn hoặc bằng 0');
          return false;
        }
        gia=gia_bia;
      }
      else{
        loai_gia=0;
        chiet_khau=0;
        gia_bia=0;
        if(gia_nhap<=0){
          alert('Giá nhập không được nhỏ hơn hoặc bằng 0');
          return false;
        }
      }
      // kiểm tra nếu đã tồn tại sản phẩm thì không cho add
      var co=0;
      jQuery('.id_san_pham').each(function(){
        var id_san_pham_check=jQuery(this).val();
        if(id_san_pham_check==id_san_pham){
          co=1;
          alert('Sản phẩm đã tồn tại');
          return false;
        }
      });
      // kiểm tra điều kiên để được add
      if(co==0){
        if(jQuery.isNumeric(id_san_pham) && jQuery.isNumeric(so_luong) && jQuery.isNumeric(loai_gia) && jQuery.isNumeric(gia_nhap) && jQuery.isNumeric(gia_bia) && jQuery.isNumeric(chiet_khau) && id_san_pham>0 && so_luong>0 && loai_gia>=0 && gia_nhap>=0 && gia_bia>=0 && chiet_khau>=0){
          so_dong++;
          var input='<div class="san_pham_thu_'+so_dong+'"><input type="hidden" name="id_san_pham[]" class="id_san_pham" value="'+id_san_pham+'">'
                   +'<input type="hidden" name="so_luong[]" class="so_luong" value="'+so_luong+'">'
                   +'<input type="hidden" name="loai_gia[]" class="loai_gia" value="'+loai_gia+'">'
                   +'<input type="hidden" name="gia_nhap[]" class="gia_nhap" value="'+gia_nhap+'">'
                   +'<input type="hidden" name="gia_bia[]" class="gia_bia" value="'+gia_bia+'">'
                   +'<input type="hidden" name="chiet_khau[]" class="chiet_khau" value="'+chiet_khau+'"></div>';
          jQuery('#danh_sach_san_pham').append(input);


          var ten_san_pham=jQuery('#dev-table-filter-2').val();
          var don_vi_tinh=jQuery('#don_vi_tinh').val();
          var tr='<tr class="san_pham_thu_'+so_dong+'">'
                +'<td>'+ten_san_pham+'</td>'
                +'<td>'+don_vi_tinh+'</td>'
                +'<td>'+so_luong+'</td>'
                +'<td>'+gia+'</td>'
                +'<td><a href="#" onclick="xoaSanPhamNhap('+so_dong+')">xóa</a></td>'
                +'</tr>';
          jQuery('#danh_sach_san_pham_nhap tbody').append(tr);
        }
        else{
          alert('Lỗi, vui lòng chọn sản phẩm lại');
        }
      }
        
    });

    // click nút btn_in_don_hang
    jQuery('#btn_in_don_hang').on('click', function(){
      var length=jQuery('#danh_sach_san_pham_nhap tbody tr').length;
      if(length>0){
        //window.print();
        jQuery('#xuat_hang_hoa').submit();
        // hủy hết sản phẩm đã nhập
        jQuery('#danh_sach_san_pham_nhap tbody tr').html('');
        jQuery('#danh_sach_san_pham').html('');

        jQuery('#dev-table-filter').val('');
        jQuery('#dia_chi').val('');
        jQuery('#di_dong').val('');
        jQuery('#dev-table-filter-2').val('');
        jQuery('#ma_san_pham').val('');
        jQuery('#ma_vach').val('');
        jQuery('#so_luong').val('');
        jQuery('#gia_nhap').val('');
        jQuery('#gia_bia').val('');
        jQuery('#chiet_khau').val('');
      }
      else{
        alert('Chưa có sản phẩm trong danh sách nhập');
      }
    });

    // click nut btn_huy_don_hang
    jQuery('#btn_huy_don_hang').on('click', function(){
      jQuery('#danh_sach_san_pham_nhap tbody tr').html('');
      jQuery('#danh_sach_san_pham').html('');

      jQuery('#dev-table-filter').val('');
      jQuery('#dia_chi').val('');
      jQuery('#di_dong').val('');
      jQuery('#dev-table-filter-2').val('');
      jQuery('#ma_san_pham').val('');
      jQuery('#ma_vach').val('');
      jQuery('#so_luong').val('');
      jQuery('#gia_nhap').val('');
      jQuery('#gia_bia').val('');
      jQuery('#chiet_khau').val('');
    });

    xoaSanPhamNhap=function(row){
      jQuery('.san_pham_thu_'+row).remove();
    }
  })
</script>