<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">NHẬP HÀNG HÓA</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Nhà cung cấp</label> 
    <div class="filter">
      <input type="text" class="form-control" id="dev-table-filter" data-action="filter" data-filters="#dev-table" placeholder="Nhập tên nhà cung cấp, số điện thoại, địa chỉ" />
      <table class="table table-hover cursor dev-table" id="dev-table">        
        <tbody>
        </tbody>
      </table>
    </div>





























  </div>
  <div class="form-group">
    <label>Địa chỉ</label>
    <input type="text" name="name" title="Địa chỉ" class="form-control">
  </div>
  <div class="form-group">
    <label>Số điện thoại</label>
    <input type="text" name="name" title="Số điện thoại" class="form-control">
  </div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Tên sản phẩm</label>
    <div class="filter">
      <input type="text" class="form-control" id="dev-table-filter-2" data-action="filter-2" data-filters="#dev-table-2" placeholder="Nhập tên sản phẩm, mã sản phẩm, mã vạch" />
      <table class="table table-hover cursor dev-table" id="dev-table-2">        
        <tbody>
        </tbody>
      </table>
    </div>





  </div>
  <div class="form-group">
    <label>Mã sản phẩm</label>
    <input type="text" name="name" title="Mã sản phẩm" class="form-control">
  </div> 
  <div class="form-group">
    <label>Mã vạch</label>
    <input type="text" name="name" title="Mã sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label>Số lượng</label>
    <input type="number" name="name" title="Số lượng" class="form-control">
  </div>           
  <div class="form-group">
    <label>Giá sản phẩm</label>
    <input type="number" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <div class="btn btn-danger btn-block">Thêm</div>
  </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <hr>
  <span class="title">DANH SÁCH HÀNG XUẤT</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="table-responsive">
    <table class="table table-border">
      <thead>
        <tr class="active">
          <th>Sản phẩm</th>
          <th>Đơn vị tính</th>
          <th>Số lượng</th>
          <th>Giá</th>
          <th>Hủy</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr> -->
      </tbody>
    </table>
  </div>            
</div> 
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="btn btn-default">Hủy đơn hàng</div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-right">
  <div class="btn btn-danger">In đơn hàng</div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function(){
    var tr='<tr>'
          +   '<td data-title="Tên nhà cung cấp">Nguyễn Hoàng Duy Thiện</td>'
          +   '<td class="numeric" data-title="Mobile (RM/30sec)">'
          +   '01699580585</td>'
          +   '<td data-title="Địa chỉ">Cầu ngang</td>'
          + '</tr>'
          + '<tr>'
          +   '<td data-title="Tên nhà cung cấp">Phan Văn Thanh</td>'
          +   '<td class="numeric" data-title="Mobile (RM/30sec)">01699580585</td>'
          +   '<td data-title="Địa chỉ">Châu hưng, châu điền, cầu kè, trà vinh</td>'
          + '</tr>'
          + '<tr>'
          +   '<td data-title="Tên nhà cung cấp">Phan Văn Thanh</td>'
          +   '<td class="numeric" data-title="Mobile (RM/30sec)">01699580585</td>'
          +   '<td data-title="Địa chỉ">Cầu kè</td>'
          + '</tr>';
    jQuery('#dev-table tbody').append(tr);
    jQuery('#dev-table tbody tr').on('click', function(){
      var text=jQuery(this).find('td:first-child').text();
      jQuery('#dev-table-filter').val(text);
    });

    jQuery('#dev-table-2 tbody').append(tr);
    jQuery('#dev-table-2 tbody tr').on('click', function(){
      var text=jQuery(this).find('td:first-child').text();
      jQuery('#dev-table-filter-2').val(text);
    });
  })
</script>