
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <a class="btn btn-default" href="/hang-hoa">back</a>
  <div class="btn btn-primary">save</div>
</div>
<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
  <span class="title">THÊM SẢN PHẨM</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
  <div class="form-group">
    <label>Tên sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label>Mã sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">              
    <span class="btn btn-default btn-file">
      Browse <input type="file">
    </span>
    <img src="img/orther/girl.jpg" alt="..." class="img-circle" width="140px" height="140px">
  </div>
  <div class="form-group">
    <label>Giá sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label for="comment">Comment:</label>
    <textarea class="form-control" rows="5" id="comment"></textarea>
  </div>
  <div class="form-group">
    <label>Email</label>
    <input type="email" name="email" title="Tên sản phẩm" class="form-control">
  </div>
  <!-- checkbox inline -->
  <div class="form-group">
    <label class="checkbox-inline">
      <input type="checkbox" value="">Option 1
    </label>
    <label class="checkbox-inline">
      <input type="checkbox" value="">Option 2
    </label>
    <label class="checkbox-inline disabled">
      <input type="checkbox" value="" disabled>Option 3
    </label>
  </div>
  <!-- radio inline -->
  <div class="form-group">
    <label class="radio-inline"><input type="radio" name="optradio">Option 1</label>
    <label class="radio-inline"><input type="radio" name="optradio">Option 2</label>
    <label class="radio-inline disabled"><input type="radio" name="optradio" disabled>Option 3</label>
  </div>  
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
    <a class="btn btn-default" href="/hang-hoa">back</a>
    <div class="btn btn-primary">save</div>
  </div>