<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">XUẤT HÀNG HÓA</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Khách hàng</label>&nbsp;&nbsp;&nbsp;&nbsp;
    <label class="checkbox-inline">
      <input type="checkbox" value="">Bán lẻ
    </label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label>Địa chỉ</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Tên sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label>Mã sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>            
  <div class="form-group">
    <label>Giá sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <div class="btn btn-danger btn-block">Thêm</div>
  </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <hr>
  <span class="title">DANH SÁCH HÀNG XUẤT</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="table-responsive">
    <table class="table table-border">
      <thead>
        <tr class="active">
          <th>Sản phẩm</th>
          <th>Đơn vị tính</th>
          <th>Số lượng</th>
          <th>Giá</th>
          <th>Hủy</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr> -->
      </tbody>
    </table>
  </div>            
</div> 
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="btn btn-default">Hủy đơn hàng</div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-right">
  <div class="btn btn-danger">In đơn hàng</div>
</div>
<script type="text/javascript">
// xử lý
  /*
    - Khi vừa load trang:
      + get dữ liệu nhà cung cấp theo id_kho của nhân viên. dữ liệu get gồm những cột: ho_ten, di_dong, dia_chi, id_kenh_phan_phoi.
    - Khi nhân viên nhà cung cấp xong:
      + get dữ liệu bảng sản phẩm. dữ liệu get gồm: ten_san_pham, ma_san_pham, ma_vach, so_luong, gia_ban theo id_kenh_phan_phoi vừa get ở trên.
      + sau khi get xong lưu lại.
      + trước khi get dữ liệu từng kênh thì phải kiểm tra dữ liệu kênh đó có get chưa nếu gét rồi thì khỏi get nữa mà lấy biến củ ra sử dụng.
      + kết luận: mỗi user chỉ cần get 4 lần là cao nhất
    - khi nhân viên chọn sản phẩm:
      + phải lấy dữ liệu sản phẩm lại 1 lần nữa. cột dữ liệu cần lấy chỉ 1 cột: so_luong.
      + so sánh số lượng tồn và số lượng nhập vô nếu so_luong muốn bán lớn hơn số lượng tồn thì không cho add, ngược lại add
  */
</script>