<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">XUẤT HÀNG HÓA</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Khách hàng</label>&nbsp;&nbsp;&nbsp;&nbsp;
    <label class="checkbox-inline">
      <input type="checkbox" value="">Bán lẻ
    </label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label>Địa chỉ</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Tên sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <label>Mã sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>            
  <div class="form-group">
    <label>Giá sản phẩm</label>
    <input type="text" name="name" title="Tên sản phẩm" class="form-control">
  </div>
  <div class="form-group">
    <div class="btn btn-danger btn-block">Thêm</div>
  </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <hr>
  <span class="title">DANH SÁCH HÀNG XUẤT</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="table-responsive">
    <table class="table table-border">
      <thead>
        <tr class="active">
          <th>Sản phẩm</th>
          <th>Đơn vị tính</th>
          <th>Số lượng</th>
          <th>Giá</th>
          <th>Hủy</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr> -->
      </tbody>
    </table>
  </div>            
</div> 
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="btn btn-default">Hủy đơn hàng</div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-right">
  <div class="btn btn-danger">In đơn hàng</div>
</div>         