<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">XUẤT HÀNG HÓA</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Khách hàng</label>&nbsp;&nbsp;&nbsp;&nbsp;
    <label class="checkbox-inline">
      <input type="checkbox" id="ban_le"><label for="ban_le">Bán lẻ</label>
    </label>
    <div class="filter">
      <input type="text" class="form-control" id="ho_ten" data-action="filter" data-filters="#danh_sach_khach_hang" placeholder="Nhập tên khách hàng, số điện thoại, địa chỉ" />
      <table class="table table-hover cursor dev-table" id="danh_sach_khach_hang">
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
  <div class="form-group">
    <label>Địa chỉ</label>
    <input type="text" id="dia_chi" title="Địa chỉ" class="form-control">
  </div>
  <div class="form-group">
    <label>Số điện thoại</label>
    <input type="text" id="di_dong" title="Số điện thoại" class="form-control">
  </div>
  <div class="form-group">
    <label>Kênh phân phối</label>
    <input type="text" id="kenh_phan_phoi" title="Kênh phân phối" class="form-control" disabled>
  </div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label>Tên sản phẩm</label>
    <div class="filter">
      <input type="text" class="form-control" id="ten_san_pham" data-action="filter" data-filters="#danh_sach_san_pham" placeholder="Nhập tên sản phẩm, mã sản phẩm, mã vạch" />
      <table class="table table-hover cursor dev-table" id="danh_sach_san_pham">
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
  <div class="form-group">
    <label>Mã sản phẩm</label>
    <input type="text" id="ma_san_pham" title="Mã sản phẩm" class="form-control">
  </div>  
  <div class="form-group">
    <label>Mã vạch</label>
    <input type="text" id="ma_vach" title="Mã vạch" class="form-control">
  </div>
  <div class="form-group">
    <label>Số lượng</label>
    <input type="number" id="so_luong" min="0" title="Số lượng" class="form-control">
  </div>          
  <div class="form-group">
    <label>Giá sản phẩm</label>
    <input type="number" id="gia_xuat" min="0" title="Giá bán" class="form-control">
  </div>
  <div class="form-group">
    <div class="btn btn-danger btn-block">Thêm</div>
  </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <hr>
  <span class="title">DANH SÁCH HÀNG XUẤT</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="table-responsive">
    <table class="table table-border" id="danh_sach_hang_xuat">
      <thead>
        <tr class="active">
          <th>Sản phẩm</th>
          <th>Đơn vị tính</th>
          <th>Số lượng</th>
          <th>Giá</th>
          <th>Hủy</th>
        </tr>
      </thead>
      <tbody>
        <!-- <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr> -->
      </tbody>
    </table>
  </div>            
</div> 
<form method="post" action="<?php echo $this->url('hang_hoa', array('action'=>'xuat-hang-hoa')); ?>" target="_blank" name="xuat_hang_hoa" id="xuat_hang_hoa">
  <input type="hidden" name="id_khach_hang" id="id_khach_hang">
  <div id="danh_sach_input_post"></div>
</form>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="btn btn-default" id="btn_huy_don_hang">Hủy đơn hàng</div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-right">
  <div class="btn btn-danger" id="btn_in_don_hang">In đơn hàng</div>
</div>
<script type="text/javascript">
  // xử lý
  jQuery(document).ready(function(){
    // lấy dữ liệu khách hàng
      var co_xu_ly=0;
      var xhr1;           
      if(xhr1 && xhr1.readyState != 4){
        xhr1.abort(); //huy lenh ajax truoc do
      }
      xhr1 = $.ajax({
        url:"<?php echo $this->url('hang_hoa', array('action'=>'danh-sach-khach-hang')); ?>",
        type:'POST',
        dataType:'json',
        data:{
            
        },
        success:function(data){
          if(data.error==''){
            jQuery.each( data.danh_sach_khach_hang, function( key, value){
              var tr='<tr>'
                    +   '<td data-title="Tên khách hàng" style="width:40%;"><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.id_khach_hang+'</div><div>'+value.ho_ten+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.id_kenh_phan_phoi+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.kenh_phan_phoi+'</div></td>'
                    +   '<td data-title="Mobile (RM/30sec)" class="numeric" style="width:20%;">'+value.di_dong+'</td>'
                    +   '<td data-title="Địa chỉ" style="width:40%;">'+value.dia_chi+'</td>';
              jQuery('#danh_sach_khach_hang tbody').append(tr);
            });
            // khi click chọn một khách hàng nào đó
            jQuery('#danh_sach_khach_hang tbody tr').on('click', function(){                
              // xóa tất cả dữ liệu trước
              jQuery('#danh_sach_hang_xuat tbody').html('');
              jQuery('#danh_sach_input_post').html('');
              jQuery('#id_khach_hang').val('');
              // lấy id mới nhất
              var id_khach_hang=jQuery(this).find('td:first-child div:first-child').text().trim();
              var ho_ten=jQuery(this).find('td:first-child div:nth-child(2)').text().trim();
              var id_kenh_phan_phoi=jQuery(this).find('td:first-child div:nth-child(3)').text().trim();
              var kenh_phan_phoi=jQuery(this).find('td:first-child div:nth-child(4)').text().trim();
              var di_dong=jQuery(this).find('td:nth-child(2)').text().trim();
              var dia_chi=jQuery(this).find('td:nth-child(3)').text().trim();
                           
              if(jQuery.isNumeric(id_khach_hang)){
                jQuery('#id_khach_hang').val(id_khach_hang);
                jQuery('#ho_ten').val(ho_ten);
                jQuery('#dia_chi').val(dia_chi);
                jQuery('#di_dong').val(di_dong);
                jQuery('#kenh_phan_phoi').val(kenh_phan_phoi);
                // lấy dữ liệu sản phẩm phù hợp với kênh phân phối của khách hàng        
                  var xhr2;           
                  if(xhr2 && xhr2.readyState != 4){
                      xhr2.abort(); //huy lenh ajax truoc do
                  }
                  xhr2 = $.ajax({
                    url:"<?php echo $this->url('hang_hoa', array('action'=>'danh-sach-san-pham-xuat')); ?>",
                    type:'POST',
                    dataType:'json',
                    data:{
                        'id_kenh_phan_phoi': id_kenh_phan_phoi,
                    },
                    success:function(data){
                      if(data.error==''){
                        jQuery('#danh_sach_san_pham tbody').html('');
                        jQuery.each( data.danh_sach_san_pham, function( key, value){
                          var tr='<tr>'
                                +   '<td data-title="Tên sản phẩm" style="width:60%;"><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.id_san_pham+'</div><div>'+value.ten_san_pham+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.don_vi_tinh+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.gia_xuat+'</div><div class="hidden-xs hidden-sm hidden-md hidden-lg">'+value.ton_kho+'</div></td>'
                                +   '<td data-title="Mã sản phẩm" style="width:20%;">'+value.ma_san_pham+'</td>'
                                +   '<td data-title="Mã vạch" style="width:20%;">'+value.ma_vach+'</td>'; 
                          jQuery('#danh_sach_san_pham tbody').append(tr);
                        });
                      }
                    },
                  });
              }
            });
          }         
        },
      });     

    // btn_in_don_hang
      jQuery('#btn_in_don_hang').on('click', function(){
        jQuery('#xuat_hang_hoa').submit();
      });    
  })
</script>