
          <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
              <div class="nav-side-menu">
                <!-- <div class="brand text-left">Hàng hóa</div> -->
                <!-- <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i> -->
                <div class="menu-list">        
                  <ul id="menu-content" class="menu-content out"> <!-- menu-content collapse out -->
                    <li class="active" onclick="setLocation('index.html')">
                      <a href="#">
                      <i class="fa fa-dashboard fa-lg"></i> Danh sách hàng
                      </a>
                    </li>
                    <li   onclick="setLocation('index.html')" data-toggle="collapse" data-target="#products" class="collapsed">
                      <a href="#"><i class="fa fa-gift fa-lg"></i> Bảng giá </a>
                    </li>
                    <li  onclick="setLocation('xuat-hang.html')" data-toggle="collapse" data-target="#service" class="collapsed">
                      <a href="#"><i class="fa fa-globe fa-lg"></i> Nhập hàng </a>
                    </li> 
                    <li  onclick="setLocation('xuat-hang.html')" data-toggle="collapse" data-target="#new" class="collapsed">
                      <a href="#"><i class="fa fa-car fa-lg"></i> Xuất hàng </a>
                    </li>
                    <li onclick="setLocation('xuat-hang.html')">
                      <a href="#"><i class="fa fa-user fa-lg"></i> Đổi trả hàng</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-8 col-lg-9">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                <div class="btn btn-default">import</div>
                <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
                <a href="add.html" class="btn btn-primary">add new</a>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span class="title">HÀNG HÓA</span>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
              <table id="example" class="table table-hover table-striped table-bordered cursor" cellspacing="0" width="100%">
                <thead>
                  <tr>
                    <th>Tên sản phẩm</th>
                    <th>Mã sản phẩm</th>
                    <th>Giá</th>
                    <th>Số lượng</th>
                    <th>Ngày tạo</th>
                    <th>Ngày cập nhật</th>
                  </tr>
                </thead>     
                <tbody>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiger Nixon</td>
                    <td>System Architect</td>
                    <td>Edinburgh</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>$320,800</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 2</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 3</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 4</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 5</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 6</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 7</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 8</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>

                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 9</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 10</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 11</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 12</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr><tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr><tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>

                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>

                </tbody>
              </table>
            </div>
          </div>     
<script type="text/javascript">
  jQuery(document).ready(function(){
    $('#example').DataTable();
  })
</script>