
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
                <div class="btn btn-default">import</div>
                <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
                <a href="add.html" class="btn btn-primary">add new</a>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span class="title">HÀNG HÓA</span>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
              <table id="example" class="table table-hover table-striped table-bordered cursor" cellspacing="0" width="100%">
                <thead>
                  <tr>
                    <th>Tên sản phẩm</th>
                    <th>Mã sản phẩm</th>
                    <th>Giá</th>
                    <th>Số lượng</th>
                    <th>Ngày tạo</th>
                    <th>Ngày cập nhật</th>
                  </tr>
                </thead>     
                <tbody>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiger Nixon</td>
                    <td>System Architect</td>
                    <td>Edinburgh</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>$320,800</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 2</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 3</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 4</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 5</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 6</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 7</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 8</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>

                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 9</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 10</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 11</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 12</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr><tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr><tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>

                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>
                  <tr onclick="setLocation('edit.html')">
                    <td>Tiếng việt lớp 1</td>
                    <td>tvl01</td>
                    <td>$10000</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>2012/04/25</td>
                  </tr>

                </tbody>
              </table>