<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">CHI TIẾT DOANH THU <?php echo $this->date; ?></span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="doanh_thu_table" class="table table-hover table-bordered" cellspacing="0" width="100%"> <!--  table-striped -->
  <thead>
    <tr>
      <th>Ngày</th>
      <th>Mã đơn hàng</th>
      <th>Khách hàng</th>
      <th>Kênh phân phối</th>
      <th>Doanh thu</th>
      <th>Nguồn vốn</th> 
      <th>Lợi nhuận</th>    
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_chi_tiet_doanh_thu as $doanh_thu) { ?>
    <tr>
      	<td>
      	<?php 
      		$date = new DateTime($doanh_thu['ngay_xuat']);
      		echo $date->format('d-m-Y'); 
      	?>
      	</td>
      	<td><a href="<?php echo $this->url('ban_hang', array('action'=>'chi-tiet-don-hang', 'id'=>$doanh_thu['id_hoa_don'])); ?>"><?php echo $doanh_thu['ma_hoa_don']; ?></a> </td>
      	<td><a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-khach-hang', 'id'=>$doanh_thu['id_khach_hang'])); ?>"><?php echo $doanh_thu['ho_ten']; ?></a> </td>
      	<td><?php echo $doanh_thu['kenh_phan_phoi']; ?></td>
      	<td>
      	<?php 
      		echo number_format($doanh_thu['doanh_thu'],0,","," "); 
      	?>
      	</td>
      	<td>
      	<?php 
      		echo number_format($doanh_thu['von'],0,","," "); 
      	?>
      	</td>
      	<td>
      	<?php 
      		$loi_nhuan=(float)$doanh_thu['doanh_thu']-(float)$doanh_thu['von']; 
      		echo number_format($loi_nhuan,0,","," ");
      	?>
      	</td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery("#doanh_thu_table").DataTable({
	      responsive: true,
	      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
	    });
	})
</script>