<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">HÓA ĐƠN</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Ngày xuất hóa đơn</th>
      <th>Mã hóa đơn</th>
      <th class="hidden-xs">Khách hàng</th>
      <th>Thanh toán</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_hoa_don as $key => $hoa_don) { ?>
    <tr>
      <td>
      <?php 
        $date = new DateTime($hoa_don['ngay_xuat']);
        echo $date->format('d-m-Y');
      ?>
      </td>
      <td>
        <a href="<?php echo $this->url('ban_hang', array('action'=>'chi-tiet-hoa-don', 'id'=>$hoa_don['id_hoa_don'])); ?>"><?php echo $hoa_don['ma_hoa_don']; ?></a>      
      </td>
      <td class="hidden-xs">
      <a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-khach-hang', 'id'=>$hoa_don['id_khach_hang'])); ?>"><?php echo $hoa_don['ho_ten']; ?></a> 
      </td>
      <td>
      <?php 
        if($hoa_don['state']==0){
          echo '<span class="label label-danger hidden-xs">Chưa thanh toán</span><span class="label label-danger hidden-sm hidden-md hidden-lg">Chưa</span>';
        }
        elseif($hoa_don['state']==1){
          echo '<span class="label label-warning hidden-xs">Thanh toán một phần</span><span class="label label-warning hidden-sm hidden-md hidden-lg">Một phần</span>';
        }
        else{
          echo '<span class="label label-success hidden-xs">Đã thanh toán</span><span class="label label-success hidden-sm hidden-md hidden-lg">Xong</span>';
        }
      ?>
      </td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
    });
  })                
</script>