<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">DOANH THU</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
   <?php
	$form=$this->form;
	$form->setAttribute('action', $this->url("ban_hang", array('action'=>'index')));
	$form->setAttribute('class','form');
	$form->setAttribute('role','form');
	$form->setAttribute('method','post');
	$form->prepare();
	echo $this->form()->openTag($form);
	?> 
		<div class="form-group">
			<?php echo $this->formLabel($form->get('loai_doanh_thu')); ?>
	      	<?php 
	      		$form->get('loai_doanh_thu')->setAttribute('id','chon_loai_doanh_thu');
	      		echo $this->formSelect($form->get('loai_doanh_thu')); 
	      	?>
	      	<div class="text-danger">
	        <?php 	        	
	        	echo $this->formElementErrors($form->get('loai_doanh_thu')); 
	        ?>
	      	</div>
	    </div>

	<?php echo $this->form()->closeTag($form); ?>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		<label>Chọn kênh phân phối</label>
		<select id="kenh_phan_phoi" class="form-control">
			<option value="tat_ca_doanh_thu">Tất cả</option>
			<?php
				foreach ($this->danh_sach_kenh_phan_phoi as $key => $kenh_phan_phoi) {
				?>
					<option value="doanh_thu_kenh_<?php echo $key; ?>">
						<?php 
							echo $kenh_phan_phoi;
						?>
					</option>
				<?php
				}
			?>
		</select>
	</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<div id="tat_ca_doanh_thu" class="doanh_thu">
	<table class="table table-hover table-bordered doanh_thu_table" cellspacing="0" width="100%"> <!--  table-striped -->
	  <thead>
	    <tr>
	      <th>Thời gian</th>
	      <th>Số hóa đơn</th>
	      <th>Doanh thu</th>
	      <th>Nguồn vốn</th> 
	      <th>Lợi nhuận</th>    
	    </tr>
	  </thead>     
	  <tbody>
	  <?php foreach ($this->tat_ca_doanh_thu as $doanh_thu) { ?>
	    <tr>
	      	<td>
	      		<?php $date=str_replace('-', '', $doanh_thu['thoi_gian']); ?>
		      	<a href="<?php echo $this->url('ban_hang', array('action'=>'chi-tiet-doanh-thu', 'id'=>$date)); ?>"><?php echo $doanh_thu['thoi_gian']; ?></a> 
	      	</td>
	      	<td><?php echo number_format($doanh_thu['so_hoa_don'],0,","," "); ?></td>
	      	<td><?php echo number_format($doanh_thu['doanh_thu'],0,","," "); ?></td>
	      	<td><?php echo number_format($doanh_thu['von'],0,","," "); ?></td>
	      	<td>
	      		<?php 
	      			$loi_nhuan=(float)$doanh_thu['doanh_thu']-(float)$doanh_thu['von']; 
	      			echo number_format($loi_nhuan,0,","," ");
	      		?>
	      	</td>
	    </tr>
	  <?php }?>                  
	  </tbody>
	</table>
</div>

<?php
	foreach ($this->danh_sach_doanh_thu_theo_kenh as $key => $value) {
	?>
		<div id="doanh_thu_kenh_<?php echo $key; ?>" class="hidden-xs hidden-sm hidden-md hidden-lg doanh_thu">
			<table class="table table-hover table-bordered doanh_thu_table" cellspacing="0" width="100%"> <!--  table-striped -->
			  	<thead>		  	
			    	<tr>
			      		<th>Thời gian</th>
			      		<th>Số hóa đơn</th>
			      		<th>Doanh thu</th> 
			      		<th>Nguồn vốn</th> 
			      		<th>Lợi nhuận</th>    
			    	</tr>
			  	</thead>     
			  	<tbody>
			  	<?php foreach ($value as $doanh_thu) { ?>
			    	<tr>
			      		<td><?php echo $doanh_thu['thoi_gian']; ?></td>
			      		<td><?php echo number_format($doanh_thu['so_hoa_don'],0,","," "); ?></td>
			      		<td><?php echo number_format($doanh_thu['doanh_thu'],0,","," "); ?></td>
			      		<td><?php echo number_format($doanh_thu['von'],0,","," "); ?></td>
			      		<td>
			      		<?php 
			      			$loi_nhuan=(float)$doanh_thu['doanh_thu']-(float)$doanh_thu['von']; 
			      			echo number_format($loi_nhuan,0,","," ");
			      		?>
			      		</td>
			    	</tr>
			  	<?php }?>                  
			  	</tbody>
			</table>
		</div>
	<?php
	}
?>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery( "#chon_loai_doanh_thu" ).change(function() {
		  jQuery('#loai_doanh_thu').submit();
		});

		jQuery(".doanh_thu_table").DataTable({
	      responsive: true,
	      "lengthMenu": [[-1, 10, 25, 50, 100, 200], ["All", 10, 25, 50, 100, 200]]
	    });

		jQuery('#kenh_phan_phoi').change(function(){
			jQuery('.doanh_thu').addClass('hidden-xs hidden-sm hidden-md hidden-lg');
			var id_table=jQuery(this).val();
			jQuery('#'+id_table).removeClass('hidden-xs hidden-sm hidden-md hidden-lg');
		});
	})
</script>