<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">PHIẾU ĐỔI TRẢ</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Ngày xuất</th>
      <th>Mã hóa đơn</th>
      <th class="hidden-xs">Khách hàng</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_phieu_doi_tra as $key => $phieu_doi_tra) { ?>
    <tr>
      <td>
      <?php 
        $date = new DateTime($phieu_doi_tra['ngay_xuat']);
        echo $date->format('d-m-Y');
      ?>
      </td>
      <td>
        <a href="<?php echo $this->url('ban_hang', array('action'=>'chi-tiet-phieu-doi-tra', 'id'=>$phieu_doi_tra['id_phieu_doi_tra'])); ?>"><?php echo $phieu_doi_tra['ma']; ?></a>      
      </td>
      <td class="hidden-xs">
      <a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-khach-hang', 'id'=>$phieu_doi_tra['id_khach_hang'])); ?>"><?php echo $phieu_doi_tra['ho_ten']; ?></a> 
      </td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
    });
  })                
</script>