<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="btn btn-default">import</div>
  <div class="btn btn-default" onclick="tableToExcel('example', 'export')">export</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <span class="title">PHIẾU NHẬP</span>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">&nbsp;</div>
<table id="example" class="table table-hover table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Ngày xuất phiếu nhập</th>
      <th>Mã phiếu nhập</th>
      <th>Nhà cung cấp</th>
      <th>Thanh toán</th>
    </tr>
  </thead>     
  <tbody>
  <?php foreach ($this->danh_sach_phieu_nhap as $key => $phieu_nhap) { ?>
    <tr>
      <td>
      <?php 
        $date = new DateTime($phieu_nhap['ngay_nhap']);
        echo $date->format('d-m-Y');
      ?>
      </td>
      <td>
        <a href="<?php echo $this->url('ban_hang', array('action'=>'chi-tiet-phieu-nhap', 'id'=>$phieu_nhap['id_phieu_nhap'])); ?>"><?php echo $phieu_nhap['ma_phieu_nhap']; ?></a>      
      </td>
      <td>
      <a href="<?php echo $this->url('doi_tac', array('action'=>'sua-thong-tin-nha-cung-cap', 'id'=>$phieu_nhap['id_phieu_nhap'])); ?>"><?php echo $phieu_nhap['ho_ten']; ?></a> 
      </td>
      <td>
      <?php 
        if($phieu_nhap['state']==0){
          echo '<span class="label label-danger">Chưa thanh toán</span>';
        }
        elseif($phieu_nhap['state']==1){
          echo '<span class="label label-warning">Thanh toán một phần</span>';
        }
        else{
          echo '<span class="label label-success">Đã thanh toán</span>';
        }
      ?>
      </td>
    </tr>
  <?php }?>                  
  </tbody>
</table>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#example").DataTable({
      responsive: true,
      "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
    });
  })                
</script>