<div class="row">
  <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
    <div class="nav-side-menu">
      <!-- <div class="brand text-left">Hàng hóa</div> -->
      <!-- <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i> -->
      <div class="menu-list">        
        <ul id="menu-content" class="menu-content out"> <!-- menu-content collapse out -->
          <li class="active" onclick="setLocation('/permission/permission/list-user')">
            <a href="#">
            <i class="fa fa-dashboard fa-lg"></i> Danh sách tài khoản
            </a>
          </li>
          <li onclick="setLocation('/permission/permission')">
            <a href="#">
            <i class="fa fa-dashboard fa-lg"></i> Phân quyền
            </a>
          </li>
          <li onclick="setLocation('/permission/permission/edit')" data-toggle="collapse" data-target="#products" class="collapsed">
            <a href="#"><i class="fa fa-gift fa-lg"></i> Sửa quyền </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-7 col-md-8 col-lg-9">
    <div class="">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
        <div class="btn btn-default">Quay lại</div>
        <div class="btn btn-primary">Tạo mới</div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <h3>Danh sách tài khoản</h3>
      </div>
    </div>      
    <div class="">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="table-responsive" id="no-more-tables">
          <table class="table table-bordered table-hover cf">
            <thead class="cf">
              <tr>
                <th class="active">STT</th>
                <th class="active">Email</th>
                <th class="active">Kho</th>
                <th class="active text-center td-kich-hoat">Sửa</th>
              </tr>
            </thead>
            <tbody> 
              <tr>
                <td data-title="STT">1</td>
                <td data-title="Email">Admin@gmail.com</td>
                <td data-title="Kho">Chính</td>
                <td data-title="Sửa"><div class="btn btn-default td-kich-hoat">Sửa</div></td>
              </tr>              
            </tbody>
          </table>
        </div>
      </div>
    </div>    
  </div>
</div>
      