<?php
  $login_form->setAttribute('action', $this->url("permission/permission", array('action'=>'login')));
  $login_form->setAttribute('class','form');
  $login_form->setAttribute('role','form');
  $login_form->setAttribute('method','post');
  $login_form->prepare();
  echo $this->form()->openTag($login_form);
?> 
<div class="row">
    <div class="col-xs-12 hidden-sm hidden-md hidden-lg">&nbsp;</div>
    <div class="col-xs-10 col-sm-4 col-md-4 col-lg-4 col-xs-offset-1 col-sm-offset-4 col-md-offset-4 col-lg-offset-4 text-right">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="text-left">Đăng nhập</h3><br>         
          <div class="form-group has-success">
            <?php
              $login_form->get('url')->setAttribute('value',$this->url_login);
              echo $this->formInput($login_form->get('url'));
              echo $this->formInput($login_form->get('username'));
            ?>
          </div>
          <div class="form-group has-success">
            <?php echo $this->formInput($login_form->get('password')); ?>
          </div>
          <div class="form-group has-success">
            <a href="#" class="btn btn-default">Quay lại</a>&nbsp;
            <?php 
              $login_form->get('submit')->setAttribute('class','btn btn-primary');
              echo $this->formRow($login_form->get('submit')); 
            ?>
          </div>
        </div>            
      </div>
    </div>
</div>    
<?php echo $this->form()->closeTag($login_form); ?>