<?php
  	$form = $this->edit_permission_of_user_form;
  	$form->setAttribute('action', $this->url("permission/permission", array('action' => 'index')));
  	$form->prepare();
  	foreach ($this->resources as $key => $resource) {
  		$key++;
  		$level='';
  		for ($i=0; $i < $resource['level']; $i++) { 
  			$level.='__ ';
  		}
?>
		<tr>
	      <td class="text-center" data-title="STT"><?php echo $key; ?></td>
	      <td data-title="Tài nguyên"><?php echo $level.$resource['resource_name']; ?></td>
	      <td data-title="Kích hoạt" class="text-center checkbox-is-check">
	        <?php echo $this->formElement($form->get($resource['parent_id'].'_'.$resource['resource'])); ?>
	      </td>
	    </tr>
<?php
  		
  	}  
?>

<?php 
  echo $this->headScript()
  ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
  //->prependFile($this->basePath() . '/js/flat-ui/flat-ui.min.js')            
  ->prependFile($this->basePath() . '/js/sticky/jquery.sticky.js')
  ->prependFile($this->basePath() . '/js/datetime-picker/bootstrap-datetimepicker.js')
  ->prependFile($this->basePath() . '/js/function/function.js')
  ->prependFile($this->basePath() . '/js/custom/custom.js')
  ->prependFile($this->basePath() . '/js/jquery.min.js')
  ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
  ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
?>